services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s 
      timeout: 5s
      retries: 5
  backend:
    build: .
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy